<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends BaseRepository
{
//    /**
//     * return \Doctrine\ODM\MongoDB\Cursor
//     */
//    public function findAllOrderedById()
//    {
//        return $this->createQueryBuilder()
//            ->sort('id', 'ASC')
//            ->getQuery()
//            ->execute();
//    }
//
//    /**
//     * return \Doctrine\ODM\MongoDB\Cursor
//     */
//    public function findAllOrderedByTitle()
//    {
//        return $this->createQueryBuilder()
//            ->sort('title', 'ASC')
//            ->getQuery()
//            ->execute();
//    }

}