<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends BaseRepository
{

    /**
     * @param $parentId
     * @return mixed
     */
    public function getChildCountByParentId($parentId)
    {
        return $this->createQueryBuilder()
            ->field('parent_id')->equals($parentId)
            ->getQuery()
            ->execute()
            ->count();
    }

}