<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * FieldTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldTypeRepository extends DocumentRepository
{

    /**
     * @param string $orderBy
     * @param string $orderDir
     * @return \Doctrine\ODM\MongoDB\Cursor
     */
    public function findAllOrderedBy($orderBy = 'name', $orderDir = 'asc')
    {
        return $this->createQueryBuilder()
            ->sort($orderBy, $orderDir)
            ->getQuery()
            ->execute();
    }

}