<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends DocumentRepository
{

    /**
     * return \Doctrine\ODM\MongoDB\Cursor
     * @param int $categoryId
     * @return mixed
     */
    public function findAll( $categoryId = 0 )
    {
        return $this->createQueryBuilder('Product')
            ->field('parent_id')->equals( intval( $categoryId ) )
            ->sort('id', 'ASC')
            ->getQuery()
            ->execute();
    }

}