menu:
    - { title: 'ORDERS', route: '/orders', icon: 'fi fi-br-shopping-bag' }
    - { title: 'CATALOG', route: '/catalog', icon: 'fi fi-br-cube' }
    - { title: 'STATISTICS', route: '/statistics', icon: 'fi fi-br-chart-histogram' }
    - { title: 'COMMENTS', route: '/comments', icon: 'fi fi-br-comment-alt' }
    - { title: 'IMPORT_EXPORT', route: '/import-export', icon: 'fi fi-br-upload' }
    - { title: 'USERS', route: '/users', icon: 'fi fi-br-user' }
    - { title: 'TEMPLATES', route: '/templates_edit', icon: 'fi fi-br-layout-fluid' }
    - { title: 'SETTINGS', route: '/settings', icon: 'fi fi-br-settings' }
